replicaCount: 1
name: angular
image:
  repository: saif764/angular-app
  tag: latest
  pullPolicy: IfNotPresent
  container_port_name: http
service:
  type: NodePort
  port: 81
  targetPort: 80
  nodePort: 30083
resources:
  limits:
    cpu: 100m
    memory: 100Mi
  requests:
    cpu: 100m
    memory: 100Mi
