apiVersion: v1
kind: Service
metadata:
  name: angular
  namespace: angular
spec:
  selector:
    app: angular
  type: NodePort
  # sessionAffinity: None
  # sessionAffinityConfig:
  #   clientIP:
  #     timeoutSeconds: 10800
  ports:
  - name: angular-service
    protocol: TCP
    port: 81
    targetPort: http # The port on the container (Pod) where the application listens.
    # If you set the `spec.type` field to `NodePort` and you want a specific port number,
    # you can specify a value in the `spec.ports[*].nodePort` field.
    nodePort: 30083
